import type { Post, User } from "@/types";

export const DEMO_USERS: User[] = [
  {
    id: "demo-recruiter-1",
    email: "hr@techcorp.vn",
    name: "Nguyễn Thị Hoa",
    title: "HR Manager · TechCorp Vietnam",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "blue",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-2",
    email: "talent@startupxyz.vn",
    name: "Trần Văn Minh",
    title: "Talent Acquisition · StartupXYZ",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "blue",
    frame_count: 3,
    warning_count: 0,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: "demo-candidate-1",
    email: "dev@gmail.com",
    name: "Lê Quang Huy",
    title: "Frontend Developer · 3 năm kinh nghiệm",
    avatar_url: null,
    cv_url: null,
    role: "candidate",
    frame_color: null,
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "demo-candidate-2",
    email: "designer@gmail.com",
    name: "Phạm Thị Lan",
    title: "UI/UX Designer · Fresher",
    avatar_url: null,
    cv_url: null,
    role: "candidate",
    frame_color: null,
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const DEMO_POSTS: Post[] = [
  {
    id: "demo-post-1",
    author_id: "demo-recruiter-1",
    author: DEMO_USERS[0],
    type: "job_offer",
    title: "Tuyển Frontend Developer (React/Next.js) — Remote",
    content:
      "TechCorp Vietnam đang tìm kiếm Frontend Developer có kinh nghiệm với React và Next.js.\n\n**Yêu cầu:**\n- 2+ năm kinh nghiệm React/Next.js\n- Thành thạo TypeScript, Tailwind CSS\n- Có kinh nghiệm với REST API, GraphQL\n- Tiếng Anh đọc hiểu tốt\n\n**Quyền lợi:**\n- Lương cạnh tranh 20–40 triệu\n- Remote 100%\n- Macbook Pro được cung cấp\n- 13 tháng lương + thưởng dự án",
    email: "hr@techcorp.vn",
    location_name: "Hồ Chí Minh, Vietnam (Remote)",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 20000000,
    salary_max: 40000000,
    job_type: "full_time",
    status: "approved",
    comment_count: 5,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "demo-post-2",
    author_id: "demo-recruiter-2",
    author: DEMO_USERS[1],
    type: "job_offer",
    title: "Tuyển UI/UX Designer — Fresher/Junior Welcome",
    content:
      "StartupXYZ đang mở rộng team thiết kế, welcome Fresher có portfolio đẹp!\n\n**Yêu cầu:**\n- Biết dùng Figma thành thạo\n- Có portfolio (dù là project cá nhân)\n- Sáng tạo, yêu thích thiết kế sản phẩm\n- Không yêu cầu kinh nghiệm\n\n**Quyền lợi:**\n- Lương Fresher: 8–12 triệu\n- Mentor trực tiếp từ Senior Designer\n- Môi trường startup năng động\n- Flexible giờ làm việc",
    email: "talent@startupxyz.vn",
    location_name: "Hà Nội, Vietnam",
    lat: 21.0278,
    lng: 105.8342,
    salary_min: 8000000,
    salary_max: 12000000,
    job_type: "full_time",
    status: "approved",
    comment_count: 12,
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "demo-post-3",
    author_id: "demo-recruiter-1",
    author: DEMO_USERS[0],
    type: "job_offer",
    title: "Tuyển Backend Developer (Node.js/NestJS) — Part-time",
    content:
      "Cần Backend Developer hỗ trợ dự án outsource, part-time 20h/tuần.\n\n**Yêu cầu:**\n- Node.js + NestJS hoặc Express\n- PostgreSQL hoặc MongoDB\n- Docker cơ bản\n\n**Quyền lợi:**\n- Lương tính theo giờ: 100–150k/h\n- Làm việc hoàn toàn remote\n- Flexible schedule",
    email: "hr@techcorp.vn",
    location_name: "Hồ Chí Minh (Remote)",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 12000000,
    salary_max: 20000000,
    job_type: "part_time",
    status: "approved",
    comment_count: 3,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "demo-post-4",
    author_id: "demo-candidate-1",
    author: DEMO_USERS[2],
    type: "job_seeking",
    title: "Tìm việc Frontend Developer — Ưu tiên Remote",
    content:
      "Chào mọi người, mình đang tìm kiếm cơ hội mới!\n\n**Về mình:**\n- 3 năm kinh nghiệm Frontend với React, Next.js, TypeScript\n- Đã làm tại 2 công ty product (edtech & fintech)\n- Thành thạo Tailwind CSS, Figma\n- Có thể onboard trong 2 tuần\n\n**Mong muốn:**\n- Remote hoặc Hybrid (HCM)\n- Lương 25–35 triệu\n- Môi trường product, không outsource\n\nCV: xem profile của mình 👆",
    email: null,
    location_name: "Hồ Chí Minh",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 25000000,
    salary_max: 35000000,
    job_type: "full_time",
    status: "approved",
    comment_count: 8,
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: "demo-post-5",
    author_id: "demo-candidate-2",
    author: DEMO_USERS[3],
    type: "job_seeking",
    title: "UI/UX Designer Fresher tìm việc — Có portfolio Figma",
    content:
      "Mình vừa tốt nghiệp và đang tìm kiếm cơ hội đầu tiên trong ngành Design!\n\n**Về mình:**\n- Tốt nghiệp RMIT ngành Digital Media\n- Thành thạo Figma, Adobe XD\n- Đã làm 3 project cá nhân (app mobile, landing page, dashboard)\n- Đam mê thiết kế sản phẩm số\n\n**Mong muốn:**\n- Fresher position\n- Có mentor\n- HCM hoặc Remote",
    email: null,
    location_name: "Hồ Chí Minh",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: null,
    salary_max: null,
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
];
