import type { Post, User } from "@/types";

const now = Date.now();

export const DEMO_USERS: User[] = [
  {
    id: "demo-recruiter-1",
    email: "hr@techcorp.vn",
    name: "Nguyễn Thị Hoa",
    title: "HR Manager · TechCorp Vietnam",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(now - 30 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-2",
    email: "talent@startupxyz.vn",
    name: "Trần Văn Minh",
    title: "Talent Acquisition · StartupXYZ",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: null,
    frame_count: 0,
    warning_count: 2,
    created_at: new Date(now - 25 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-3",
    email: "hiring@finverse.vn",
    name: "Lê Thuỳ Dương",
    title: "Hiring Lead · Finverse",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 1,
    warning_count: 0,
    created_at: new Date(now - 18 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-4",
    email: "people@cloudnest.vn",
    name: "Võ Gia Bảo",
    title: "People Ops · CloudNest",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: null,
    frame_count: 0,
    warning_count: 1,
    created_at: new Date(now - 14 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-5",
    email: "jobs@danangmedia.vn",
    name: "Ngô Mỹ Linh",
    title: "HRBP · Danang Media",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 2,
    warning_count: 0,
    created_at: new Date(now - 11 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-6",
    email: "careers@mekonglogistics.vn",
    name: "Phạm Quốc An",
    title: "Recruitment Specialist · Mekong Logistics",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: null,
    frame_count: 0,
    warning_count: 3,
    created_at: new Date(now - 9 * 86400000).toISOString(),
  },
  {
    id: "demo-candidate-1",
    email: "dev@gmail.com",
    name: "Lê Quang Huy",
    title: "Frontend Developer · 3 năm kinh nghiệm",
    avatar_url: null,
    cv_url: null,
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(now - 5 * 86400000).toISOString(),
  },
  {
    id: "demo-candidate-2",
    email: "designer@gmail.com",
    name: "Phạm Thị Lan",
    title: "UI/UX Designer · Fresher",
    avatar_url: null,
    cv_url: null,
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(now - 2 * 86400000).toISOString(),
  },
];

const demoUser = (id: string) => DEMO_USERS.find((user) => user.id === id)!;

export const DEMO_POSTS: Post[] = [
  {
    id: "demo-post-1",
    author_id: "demo-recruiter-1",
    author: demoUser("demo-recruiter-1"),
    type: "job_offer",
    title: "Tuyển Frontend Developer (React/Next.js) — Remote",
    content:
      "TechCorp Vietnam đang tìm Frontend Developer có kinh nghiệm với React và Next.js.\n\n**Yêu cầu:**\n- 2+ năm kinh nghiệm React/Next.js\n- Thành thạo TypeScript, Tailwind CSS\n- Có kinh nghiệm với REST API, GraphQL\n- Tiếng Anh đọc hiểu tốt\n\n**Quyền lợi:**\n- Lương 20–40 triệu\n- Remote 100%\n- Macbook Pro được cung cấp\n- 13 tháng lương + thưởng dự án",
    email: "hr@techcorp.vn",
    location_name: "Hồ Chí Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 20000000,
    salary_max: 40000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 5,
    created_at: new Date(now - 2 * 3600000).toISOString(),
    updated_at: new Date(now - 2 * 3600000).toISOString(),
  },
  {
    id: "demo-post-2",
    author_id: "demo-recruiter-2",
    author: demoUser("demo-recruiter-2"),
    type: "job_offer",
    title: "Tuyển UI/UX Designer — Fresher/Junior",
    content:
      "StartupXYZ đang mở rộng team thiết kế sản phẩm.\n\n**Yêu cầu:**\n- Biết dùng Figma thành thạo\n- Có portfolio cá nhân\n- Tư duy sản phẩm tốt\n\n**Quyền lợi:**\n- Lương 10–15 triệu\n- Mentor từ Senior Designer\n- Làm việc hybrid tại Hà Nội",
    email: "talent@startupxyz.vn",
    location_name: "Hà Nội, Vietnam",
    lat: 21.0278,
    lng: 105.8342,
    salary_min: 10000000,
    salary_max: 15000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 7,
    created_at: new Date(now - 5 * 3600000).toISOString(),
    updated_at: new Date(now - 5 * 3600000).toISOString(),
  },
  {
    id: "demo-post-3",
    author_id: "demo-recruiter-3",
    author: demoUser("demo-recruiter-3"),
    type: "job_offer",
    title: "Senior Product Designer — Fintech",
    content:
      "Finverse tuyển Senior Product Designer cho team growth.\n\n**Yêu cầu:**\n- 4+ năm kinh nghiệm thiết kế sản phẩm số\n- Có kinh nghiệm dashboard/data-heavy\n- Có case study rõ ràng\n\n**Quyền lợi:**\n- Lương 30–45 triệu\n- ESOP\n- Hybrid 3 ngày/tuần",
    email: "hiring@finverse.vn",
    location_name: "Đà Nẵng, Vietnam",
    lat: 16.0544,
    lng: 108.2022,
    salary_min: 30000000,
    salary_max: 45000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(now - 8 * 3600000).toISOString(),
    updated_at: new Date(now - 8 * 3600000).toISOString(),
  },
  {
    id: "demo-post-4",
    author_id: "demo-recruiter-4",
    author: demoUser("demo-recruiter-4"),
    type: "job_offer",
    title: "Backend Engineer (Node.js/NestJS) — Part-time",
    content:
      "CloudNest cần Backend Engineer part-time cho dự án SaaS B2B.\n\n**Yêu cầu:**\n- Node.js, NestJS\n- PostgreSQL hoặc MongoDB\n- Docker cơ bản\n\n**Quyền lợi:**\n- 120k–180k/giờ\n- Remote linh hoạt",
    email: "people@cloudnest.vn",
    location_name: "Cần Thơ, Vietnam",
    lat: 10.0452,
    lng: 105.7469,
    salary_min: 12000000,
    salary_max: 22000000,
    salary_currency: "VND",
    job_type: "part_time",
    status: "approved",
    comment_count: 6,
    created_at: new Date(now - 11 * 3600000).toISOString(),
    updated_at: new Date(now - 11 * 3600000).toISOString(),
  },
  {
    id: "demo-post-5",
    author_id: "demo-recruiter-5",
    author: demoUser("demo-recruiter-5"),
    type: "job_offer",
    title: "Content Creator — Social Media Focus",
    content:
      "Danang Media tuyển Content Creator làm việc với TikTok, Reels và short-form video.\n\n**Yêu cầu:**\n- Viết caption tốt\n- Biết basic editing\n- Bắt trend nhanh\n\n**Quyền lợi:**\n- Lương 12–18 triệu\n- Team trẻ, nhiều campaign lớn",
    email: "jobs@danangmedia.vn",
    location_name: "Đà Nẵng, Vietnam",
    lat: 16.0678,
    lng: 108.2208,
    salary_min: 12000000,
    salary_max: 18000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 3,
    created_at: new Date(now - 14 * 3600000).toISOString(),
    updated_at: new Date(now - 14 * 3600000).toISOString(),
  },
  {
    id: "demo-post-6",
    author_id: "demo-recruiter-6",
    author: demoUser("demo-recruiter-6"),
    type: "job_offer",
    title: "Operations Executive — Logistics",
    content:
      "Mekong Logistics cần Operations Executive theo dõi tuyến vận chuyển nội vùng.\n\n**Yêu cầu:**\n- Excel tốt\n- Chịu được áp lực vận hành\n- Giao tiếp với tài xế/kho bãi\n\n**Quyền lợi:**\n- Lương 11–16 triệu\n- Thưởng KPI hàng tháng",
    email: "careers@mekonglogistics.vn",
    location_name: "Cần Thơ, Vietnam",
    lat: 10.034,
    lng: 105.7874,
    salary_min: 11000000,
    salary_max: 16000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 5,
    created_at: new Date(now - 18 * 3600000).toISOString(),
    updated_at: new Date(now - 18 * 3600000).toISOString(),
  },
  {
    id: "demo-post-7",
    author_id: "demo-recruiter-1",
    author: demoUser("demo-recruiter-1"),
    type: "job_offer",
    title: "QA Engineer — Web & Mobile",
    content:
      "TechCorp mở thêm vị trí QA Engineer cho team sản phẩm.\n\n**Yêu cầu:**\n- Viết test case tốt\n- Có kinh nghiệm test API/web/mobile\n- Tư duy chi tiết\n\n**Quyền lợi:**\n- Lương 15–25 triệu\n- Product stable, quy trình rõ ràng",
    email: "hr@techcorp.vn",
    location_name: "Bình Dương, Vietnam",
    lat: 10.9804,
    lng: 106.6519,
    salary_min: 15000000,
    salary_max: 25000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 2,
    created_at: new Date(now - 22 * 3600000).toISOString(),
    updated_at: new Date(now - 22 * 3600000).toISOString(),
  },
  {
    id: "demo-post-8",
    author_id: "demo-recruiter-3",
    author: demoUser("demo-recruiter-3"),
    type: "job_offer",
    title: "Business Analyst — Banking Domain",
    content:
      "Finverse tuyển Business Analyst có kinh nghiệm làm việc với stakeholder từ ngân hàng.\n\n**Yêu cầu:**\n- Viết tài liệu BRD, SRS\n- Phân tích flow nghiệp vụ tốt\n- Có kinh nghiệm domain tài chính là lợi thế",
    email: "hiring@finverse.vn",
    location_name: "Nha Trang, Vietnam",
    lat: 12.2388,
    lng: 109.1967,
    salary_min: 18000000,
    salary_max: 30000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(now - 28 * 3600000).toISOString(),
    updated_at: new Date(now - 28 * 3600000).toISOString(),
  },
  {
    id: "demo-post-9",
    author_id: "demo-recruiter-5",
    author: demoUser("demo-recruiter-5"),
    type: "job_offer",
    title: "Video Editor — Short Form Content",
    content:
      "Danang Media tuyển Video Editor chuyên short-form content.\n\n**Yêu cầu:**\n- Premiere hoặc CapCut Pro\n- Có sample video thực tế\n- Cảm nhịp tốt\n\n**Quyền lợi:**\n- Lương 10–14 triệu\n- Có bonus theo hiệu suất video",
    email: "jobs@danangmedia.vn",
    location_name: "Huế, Vietnam",
    lat: 16.4637,
    lng: 107.5909,
    salary_min: 10000000,
    salary_max: 14000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 1,
    created_at: new Date(now - 34 * 3600000).toISOString(),
    updated_at: new Date(now - 34 * 3600000).toISOString(),
  },
  {
    id: "demo-post-10",
    author_id: "demo-recruiter-4",
    author: demoUser("demo-recruiter-4"),
    type: "job_offer",
    title: "DevOps Engineer — AWS / CI/CD",
    content:
      "CloudNest tuyển DevOps Engineer phụ trách CI/CD và monitoring.\n\n**Yêu cầu:**\n- AWS cơ bản đến khá\n- CI/CD với GitHub Actions hoặc GitLab CI\n- Monitoring/alerting cơ bản\n\n**Quyền lợi:**\n- Lương 28–40 triệu\n- Remote ưu tiên",
    email: "people@cloudnest.vn",
    location_name: "Vũng Tàu, Vietnam",
    lat: 10.4114,
    lng: 107.1362,
    salary_min: 28000000,
    salary_max: 40000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 6,
    created_at: new Date(now - 40 * 3600000).toISOString(),
    updated_at: new Date(now - 40 * 3600000).toISOString(),
  },
  {
    id: "demo-post-11",
    author_id: "demo-candidate-1",
    author: demoUser("demo-candidate-1"),
    type: "job_seeking",
    title: "Tìm việc Frontend Developer — Ưu tiên Remote",
    content:
      "Mình đang tìm cơ hội Frontend mới với React, Next.js, TypeScript.\n- 3 năm kinh nghiệm product\n- Có thể join trong 2 tuần\n- Ưu tiên remote hoặc hybrid tại HCM",
    email: null,
    location_name: "Hồ Chí Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 25000000,
    salary_max: 35000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 8,
    created_at: new Date(now - 3 * 3600000).toISOString(),
    updated_at: new Date(now - 3 * 3600000).toISOString(),
  },
  {
    id: "demo-post-12",
    author_id: "demo-candidate-2",
    author: demoUser("demo-candidate-2"),
    type: "job_seeking",
    title: "UI/UX Designer Fresher tìm việc — Có portfolio",
    content:
      "Mình vừa tốt nghiệp và đang tìm vị trí Fresher UI/UX.\n- Thành thạo Figma\n- Có portfolio case study\n- Có thể làm việc tại HCM hoặc remote",
    email: null,
    location_name: "Hồ Chí Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: null,
    salary_max: null,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(now - 6 * 3600000).toISOString(),
    updated_at: new Date(now - 6 * 3600000).toISOString(),
  },
];
