import type { Application, Post, Report, User } from "@/types";

const now = Date.now();
const hoursAgo = (hours: number) => new Date(now - hours * 3600000).toISOString();
const daysAgo = (days: number) => new Date(now - days * 86400000).toISOString();

export const DEMO_USERS: User[] = [
  {
    id: "demo-recruiter-1",
    email: "hr@techcorp.vn",
    name: "Nguyễn Thị Hoa",
    title: "HR Manager · TechCorp Vietnam",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(now - 30 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-2",
    email: "talent@startupxyz.vn",
    name: "Trần Văn Minh",
    title: "Talent Acquisition · StartupXYZ",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: null,
    frame_count: 0,
    warning_count: 2,
    created_at: new Date(now - 25 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-3",
    email: "hiring@finverse.vn",
    name: "Lê Thuỳ Dương",
    title: "Hiring Lead · Finverse",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 1,
    warning_count: 0,
    created_at: new Date(now - 18 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-4",
    email: "people@cloudnest.vn",
    name: "Võ Gia Bảo",
    title: "People Ops · CloudNest",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: null,
    frame_count: 0,
    warning_count: 1,
    created_at: new Date(now - 14 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-5",
    email: "jobs@danangmedia.vn",
    name: "Ngô Mỹ Linh",
    title: "HRBP · Danang Media",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 2,
    warning_count: 0,
    created_at: new Date(now - 11 * 86400000).toISOString(),
  },
  {
    id: "demo-recruiter-6",
    email: "careers@mekonglogistics.vn",
    name: "Phạm Quốc An",
    title: "Recruitment Specialist · Mekong Logistics",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: null,
    frame_count: 0,
    warning_count: 3,
    created_at: new Date(now - 9 * 86400000).toISOString(),
  },
  {
    id: "demo-candidate-1",
    email: "dev@gmail.com",
    name: "Lê Quang Huy",
    title: "Frontend Developer · 3 năm kinh nghiệm",
    avatar_url: null,
    cv_url: null,
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(now - 5 * 86400000).toISOString(),
  },
  {
    id: "demo-candidate-2",
    email: "designer@gmail.com",
    name: "Phạm Thị Lan",
    title: "UI/UX Designer · Fresher",
    avatar_url: null,
    cv_url: null,
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: new Date(now - 2 * 86400000).toISOString(),
  },
];

const demoUser = (id: string) => DEMO_USERS.find((user) => user.id === id)!;

export const DEMO_POSTS: Post[] = [
  {
    id: "demo-post-1",
    author_id: "demo-recruiter-1",
    author: demoUser("demo-recruiter-1"),
    type: "job_offer",
    title: "Tuyển Frontend Developer (React/Next.js) — Remote",
    content:
      "TechCorp Vietnam đang tìm Frontend Developer có kinh nghiệm với React và Next.js.\n\n**Yêu cầu:**\n- 2+ năm kinh nghiệm React/Next.js\n- Thành thạo TypeScript, Tailwind CSS\n- Có kinh nghiệm với REST API, GraphQL\n- Tiếng Anh đọc hiểu tốt\n\n**Quyền lợi:**\n- Lương 20–40 triệu\n- Remote 100%\n- Macbook Pro được cung cấp\n- 13 tháng lương + thưởng dự án",
    email: "hr@techcorp.vn",
    location_name: "Hồ Chí Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 20000000,
    salary_max: 40000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 5,
    created_at: new Date(now - 2 * 3600000).toISOString(),
    updated_at: new Date(now - 2 * 3600000).toISOString(),
  },
  {
    id: "demo-post-2",
    author_id: "demo-recruiter-2",
    author: demoUser("demo-recruiter-2"),
    type: "job_offer",
    title: "Tuyển UI/UX Designer — Fresher/Junior",
    content:
      "StartupXYZ đang mở rộng team thiết kế sản phẩm.\n\n**Yêu cầu:**\n- Biết dùng Figma thành thạo\n- Có portfolio cá nhân\n- Tư duy sản phẩm tốt\n\n**Quyền lợi:**\n- Lương 10–15 triệu\n- Mentor từ Senior Designer\n- Làm việc hybrid tại Hà Nội",
    email: "talent@startupxyz.vn",
    location_name: "Hà Nội, Vietnam",
    lat: 21.0278,
    lng: 105.8342,
    salary_min: 10000000,
    salary_max: 15000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 7,
    created_at: new Date(now - 5 * 3600000).toISOString(),
    updated_at: new Date(now - 5 * 3600000).toISOString(),
  },
  {
    id: "demo-post-3",
    author_id: "demo-recruiter-3",
    author: demoUser("demo-recruiter-3"),
    type: "job_offer",
    title: "Senior Product Designer — Fintech",
    content:
      "Finverse tuyển Senior Product Designer cho team growth.\n\n**Yêu cầu:**\n- 4+ năm kinh nghiệm thiết kế sản phẩm số\n- Có kinh nghiệm dashboard/data-heavy\n- Có case study rõ ràng\n\n**Quyền lợi:**\n- Lương 30–45 triệu\n- ESOP\n- Hybrid 3 ngày/tuần",
    email: "hiring@finverse.vn",
    location_name: "Đà Nẵng, Vietnam",
    lat: 16.0544,
    lng: 108.2022,
    salary_min: 30000000,
    salary_max: 45000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(now - 8 * 3600000).toISOString(),
    updated_at: new Date(now - 8 * 3600000).toISOString(),
  },
  {
    id: "demo-post-4",
    author_id: "demo-recruiter-4",
    author: demoUser("demo-recruiter-4"),
    type: "job_offer",
    title: "Backend Engineer (Node.js/NestJS) — Part-time",
    content:
      "CloudNest cần Backend Engineer part-time cho dự án SaaS B2B.\n\n**Yêu cầu:**\n- Node.js, NestJS\n- PostgreSQL hoặc MongoDB\n- Docker cơ bản\n\n**Quyền lợi:**\n- 120k–180k/giờ\n- Remote linh hoạt",
    email: "people@cloudnest.vn",
    location_name: "Cần Thơ, Vietnam",
    lat: 10.0452,
    lng: 105.7469,
    salary_min: 12000000,
    salary_max: 22000000,
    salary_currency: "VND",
    job_type: "part_time",
    status: "approved",
    comment_count: 6,
    created_at: new Date(now - 11 * 3600000).toISOString(),
    updated_at: new Date(now - 11 * 3600000).toISOString(),
  },
  {
    id: "demo-post-5",
    author_id: "demo-recruiter-5",
    author: demoUser("demo-recruiter-5"),
    type: "job_offer",
    title: "Content Creator — Social Media Focus",
    content:
      "Danang Media tuyển Content Creator làm việc với TikTok, Reels và short-form video.\n\n**Yêu cầu:**\n- Viết caption tốt\n- Biết basic editing\n- Bắt trend nhanh\n\n**Quyền lợi:**\n- Lương 12–18 triệu\n- Team trẻ, nhiều campaign lớn",
    email: "jobs@danangmedia.vn",
    location_name: "Đà Nẵng, Vietnam",
    lat: 16.0678,
    lng: 108.2208,
    salary_min: 12000000,
    salary_max: 18000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 3,
    created_at: new Date(now - 14 * 3600000).toISOString(),
    updated_at: new Date(now - 14 * 3600000).toISOString(),
  },
  {
    id: "demo-post-6",
    author_id: "demo-recruiter-6",
    author: demoUser("demo-recruiter-6"),
    type: "job_offer",
    title: "Operations Executive — Logistics",
    content:
      "Mekong Logistics cần Operations Executive theo dõi tuyến vận chuyển nội vùng.\n\n**Yêu cầu:**\n- Excel tốt\n- Chịu được áp lực vận hành\n- Giao tiếp với tài xế/kho bãi\n\n**Quyền lợi:**\n- Lương 11–16 triệu\n- Thưởng KPI hàng tháng",
    email: "careers@mekonglogistics.vn",
    location_name: "Cần Thơ, Vietnam",
    lat: 10.034,
    lng: 105.7874,
    salary_min: 11000000,
    salary_max: 16000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 5,
    created_at: new Date(now - 18 * 3600000).toISOString(),
    updated_at: new Date(now - 18 * 3600000).toISOString(),
  },
  {
    id: "demo-post-7",
    author_id: "demo-recruiter-1",
    author: demoUser("demo-recruiter-1"),
    type: "job_offer",
    title: "QA Engineer — Web & Mobile",
    content:
      "TechCorp mở thêm vị trí QA Engineer cho team sản phẩm.\n\n**Yêu cầu:**\n- Viết test case tốt\n- Có kinh nghiệm test API/web/mobile\n- Tư duy chi tiết\n\n**Quyền lợi:**\n- Lương 15–25 triệu\n- Product stable, quy trình rõ ràng",
    email: "hr@techcorp.vn",
    location_name: "Bình Dương, Vietnam",
    lat: 10.9804,
    lng: 106.6519,
    salary_min: 15000000,
    salary_max: 25000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 2,
    created_at: new Date(now - 22 * 3600000).toISOString(),
    updated_at: new Date(now - 22 * 3600000).toISOString(),
  },
  {
    id: "demo-post-8",
    author_id: "demo-recruiter-3",
    author: demoUser("demo-recruiter-3"),
    type: "job_offer",
    title: "Business Analyst — Banking Domain",
    content:
      "Finverse tuyển Business Analyst có kinh nghiệm làm việc với stakeholder từ ngân hàng.\n\n**Yêu cầu:**\n- Viết tài liệu BRD, SRS\n- Phân tích flow nghiệp vụ tốt\n- Có kinh nghiệm domain tài chính là lợi thế",
    email: "hiring@finverse.vn",
    location_name: "Nha Trang, Vietnam",
    lat: 12.2388,
    lng: 109.1967,
    salary_min: 18000000,
    salary_max: 30000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(now - 28 * 3600000).toISOString(),
    updated_at: new Date(now - 28 * 3600000).toISOString(),
  },
  {
    id: "demo-post-9",
    author_id: "demo-recruiter-5",
    author: demoUser("demo-recruiter-5"),
    type: "job_offer",
    title: "Video Editor — Short Form Content",
    content:
      "Danang Media tuyển Video Editor chuyên short-form content.\n\n**Yêu cầu:**\n- Premiere hoặc CapCut Pro\n- Có sample video thực tế\n- Cảm nhịp tốt\n\n**Quyền lợi:**\n- Lương 10–14 triệu\n- Có bonus theo hiệu suất video",
    email: "jobs@danangmedia.vn",
    location_name: "Huế, Vietnam",
    lat: 16.4637,
    lng: 107.5909,
    salary_min: 10000000,
    salary_max: 14000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 1,
    created_at: new Date(now - 34 * 3600000).toISOString(),
    updated_at: new Date(now - 34 * 3600000).toISOString(),
  },
  {
    id: "demo-post-10",
    author_id: "demo-recruiter-4",
    author: demoUser("demo-recruiter-4"),
    type: "job_offer",
    title: "DevOps Engineer — AWS / CI/CD",
    content:
      "CloudNest tuyển DevOps Engineer phụ trách CI/CD và monitoring.\n\n**Yêu cầu:**\n- AWS cơ bản đến khá\n- CI/CD với GitHub Actions hoặc GitLab CI\n- Monitoring/alerting cơ bản\n\n**Quyền lợi:**\n- Lương 28–40 triệu\n- Remote ưu tiên",
    email: "people@cloudnest.vn",
    location_name: "Vũng Tàu, Vietnam",
    lat: 10.4114,
    lng: 107.1362,
    salary_min: 28000000,
    salary_max: 40000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 6,
    created_at: new Date(now - 40 * 3600000).toISOString(),
    updated_at: new Date(now - 40 * 3600000).toISOString(),
  },
  {
    id: "demo-post-11",
    author_id: "demo-candidate-1",
    author: demoUser("demo-candidate-1"),
    type: "job_seeking",
    title: "Tìm việc Frontend Developer — Ưu tiên Remote",
    content:
      "Mình đang tìm cơ hội Frontend mới với React, Next.js, TypeScript.\n- 3 năm kinh nghiệm product\n- Có thể join trong 2 tuần\n- Ưu tiên remote hoặc hybrid tại HCM",
    email: null,
    location_name: "Hồ Chí Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 25000000,
    salary_max: 35000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 8,
    created_at: new Date(now - 3 * 3600000).toISOString(),
    updated_at: new Date(now - 3 * 3600000).toISOString(),
  },
  {
    id: "demo-post-12",
    author_id: "demo-candidate-2",
    author: demoUser("demo-candidate-2"),
    type: "job_seeking",
    title: "UI/UX Designer Fresher tìm việc — Có portfolio",
    content:
      "Mình vừa tốt nghiệp và đang tìm vị trí Fresher UI/UX.\n- Thành thạo Figma\n- Có portfolio case study\n- Có thể làm việc tại HCM hoặc remote",
    email: null,
    location_name: "Hồ Chí Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: null,
    salary_max: null,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 4,
    created_at: new Date(now - 6 * 3600000).toISOString(),
    updated_at: new Date(now - 6 * 3600000).toISOString(),
  },
];

DEMO_USERS.push(
  {
    id: "demo-recruiter-7",
    email: "jobs@greenhub.vn",
    name: "Bui Khanh An",
    title: "Talent Partner · GreenHub",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 1,
    warning_count: 0,
    created_at: daysAgo(8),
  },
  {
    id: "demo-recruiter-8",
    email: "career@mobistack.vn",
    name: "Do Minh Chau",
    title: "Hiring Specialist · MobiStack",
    avatar_url: null,
    cv_url: null,
    role: "recruiter",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: daysAgo(6),
  },
  {
    id: "demo-candidate-3",
    email: "backend.mock@gmail.com",
    name: "Nguyen Huu Phuc",
    title: "Backend Developer · Node.js/NestJS",
    avatar_url: null,
    cv_url: "/mock-cvs/nguyen-huu-phuc-backend.txt",
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: daysAgo(4),
  },
  {
    id: "demo-candidate-4",
    email: "qa.mock@gmail.com",
    name: "Tran Thu Trang",
    title: "QA Engineer · Manual/Automation",
    avatar_url: null,
    cv_url: "/mock-cvs/tran-thu-trang-qa.txt",
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: daysAgo(3),
  },
  {
    id: "demo-candidate-5",
    email: "marketing.mock@gmail.com",
    name: "Le Gia Han",
    title: "Digital Marketing Executive",
    avatar_url: null,
    cv_url: "/mock-cvs/le-gia-han-marketing.txt",
    role: "candidate",
    frame_color: "green",
    frame_count: 0,
    warning_count: 0,
    created_at: daysAgo(2),
  }
);

DEMO_POSTS.push(
  {
    id: "demo-post-13",
    author_id: "demo-candidate-3",
    author: demoUser("demo-candidate-3"),
    type: "job_seeking",
    title: "Tim viec Backend Developer Node.js/NestJS",
    content:
      "Ung vien backend 4 nam kinh nghiem voi Node.js, NestJS va PostgreSQL.\n- Co the lam hybrid tai TP.HCM\n- San sang vao viec trong 2 tuan\n- Mong muon team co quy trinh ro rang",
    email: null,
    location_name: "Thanh pho Ho Chi Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 22000000,
    salary_max: 32000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 1,
    created_at: hoursAgo(7),
    updated_at: hoursAgo(7),
  },
  {
    id: "demo-post-14",
    author_id: "demo-candidate-4",
    author: demoUser("demo-candidate-4"),
    type: "job_seeking",
    title: "Tim viec QA Engineer Manual/Automation",
    content:
      "Ung vien QA 3 nam kinh nghiem test web, mobile va API.\n- Co the viet test case, regression checklist\n- Uu tien san pham product va team co mentor automation",
    email: null,
    location_name: "Bien Hoa, Vietnam",
    lat: 10.9447,
    lng: 106.8243,
    salary_min: 16000000,
    salary_max: 22000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 0,
    created_at: hoursAgo(9),
    updated_at: hoursAgo(9),
  },
  {
    id: "demo-post-15",
    author_id: "demo-candidate-5",
    author: demoUser("demo-candidate-5"),
    type: "job_seeking",
    title: "Tim viec Digital Marketing Executive",
    content:
      "Da tung chay campaign Facebook Ads, TikTok Ads va email automation.\n- Manh ve performance marketing\n- Co the lam viec tai HCM hoac remote 2 ngay/tuan",
    email: null,
    location_name: "Thanh pho Ho Chi Minh, Vietnam",
    lat: 10.7769,
    lng: 106.7009,
    salary_min: 15000000,
    salary_max: 20000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 0,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
  },
  {
    id: "demo-post-16",
    author_id: "demo-candidate-1",
    author: demoUser("demo-candidate-1"),
    type: "job_seeking",
    title: "Tim viec Data Analyst - san sang di cong tac",
    content:
      "Ung vien co kinh nghiem SQL, Power BI va dashboard van hanh.\n- Tung lam voi bo du lieu logistics\n- Mong muon team co KPI ro va mentor tot",
    email: null,
    location_name: "Can Tho, Vietnam",
    lat: 10.0452,
    lng: 105.7469,
    salary_min: 18000000,
    salary_max: 26000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 0,
    created_at: hoursAgo(15),
    updated_at: hoursAgo(15),
  },
  {
    id: "demo-post-17",
    author_id: "demo-recruiter-7",
    author: demoUser("demo-recruiter-7"),
    type: "job_offer",
    title: "Customer Support tieng Anh - xoay ca",
    content:
      "GreenHub tim Customer Support phuc vu khach hang quoc te.\n- Giao tiep tieng Anh tot\n- Co the xoay ca\n- Uu tien ung vien tung lam SaaS hoac e-commerce",
    email: "jobs@greenhub.vn",
    location_name: "Thanh pho Ho Chi Minh, Vietnam",
    lat: 10.7845,
    lng: 106.6953,
    salary_min: 12000000,
    salary_max: 18000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 2,
    created_at: hoursAgo(4),
    updated_at: hoursAgo(4),
  },
  {
    id: "demo-post-18",
    author_id: "demo-recruiter-8",
    author: demoUser("demo-recruiter-8"),
    type: "job_offer",
    title: "Flutter Mobile Developer - hybrid Thu Duc",
    content:
      "MobiStack can Flutter Developer cho app loyalty.\n- 2+ nam Flutter\n- Hieu Firebase, REST API\n- Team product on dinh, onboard nhanh",
    email: "career@mobistack.vn",
    location_name: "Thanh pho Thu Duc, Vietnam",
    lat: 10.8506,
    lng: 106.7719,
    salary_min: 22000000,
    salary_max: 32000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 2,
    created_at: hoursAgo(10),
    updated_at: hoursAgo(10),
  },
  {
    id: "demo-post-19",
    author_id: "demo-recruiter-2",
    author: demoUser("demo-recruiter-2"),
    type: "job_offer",
    title: "Sales Admin - van phong Thu Duc",
    content:
      "Can Sales Admin theo doi hop dong, bao gia va cham soc dau moi ban hang.\n- Excel tot\n- Giao tiep khoe\n- Co the lam viec full-time tai van phong",
    email: "talent@startupxyz.vn",
    location_name: "Thanh pho Thu Duc, Vietnam",
    lat: 10.8428,
    lng: 106.8286,
    salary_min: 10000000,
    salary_max: 14000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 1,
    created_at: hoursAgo(13),
    updated_at: hoursAgo(13),
  },
  {
    id: "demo-post-20",
    author_id: "demo-recruiter-3",
    author: demoUser("demo-recruiter-3"),
    type: "job_offer",
    title: "Data Analyst - logistics dashboard",
    content:
      "Finverse mo rong team analyst cho du an van hanh logistics.\n- SQL va BI la bat buoc\n- Co kha nang lam dashboard cho stakeholder\n- Hybrid 3 ngay tai van phong",
    email: "hiring@finverse.vn",
    location_name: "Can Tho, Vietnam",
    lat: 10.034,
    lng: 105.7874,
    salary_min: 20000000,
    salary_max: 28000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 2,
    created_at: hoursAgo(16),
    updated_at: hoursAgo(16),
  },
  {
    id: "demo-post-21",
    author_id: "demo-recruiter-4",
    author: demoUser("demo-recruiter-4"),
    type: "job_offer",
    title: "Store Supervisor - chuoi F&B",
    content:
      "CloudNest can Store Supervisor quan ly nhan su va KPI cua cua hang.\n- Co kinh nghiem shift lead hoac supervisor\n- Chiu duoc ap luc van hanh\n- Uu tien ung vien co the di ca linh hoat",
    email: "people@cloudnest.vn",
    location_name: "Da Nang, Vietnam",
    lat: 16.0544,
    lng: 108.2022,
    salary_min: 14000000,
    salary_max: 20000000,
    salary_currency: "VND",
    job_type: "full_time",
    status: "approved",
    comment_count: 3,
    created_at: hoursAgo(20),
    updated_at: hoursAgo(20),
  },
  {
    id: "demo-post-22",
    author_id: "demo-recruiter-5",
    author: demoUser("demo-recruiter-5"),
    type: "job_offer",
    title: "Graphic Designer Freelance - campaign social",
    content:
      "Danang Media tim Graphic Designer freelance theo campaign.\n- Manh ve social post, key visual va resize asset\n- Co portfolio thuc chien\n- Thanh toan theo thang, co the remote",
    email: "jobs@danangmedia.vn",
    location_name: "Da Nang, Vietnam",
    lat: 16.0678,
    lng: 108.2208,
    salary_min: 12000000,
    salary_max: 18000000,
    salary_currency: "VND",
    job_type: "part_time",
    status: "approved",
    comment_count: 1,
    created_at: hoursAgo(24),
    updated_at: hoursAgo(24),
  }
);

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: "demo-application-17",
    post_id: "demo-post-17",
    candidate_id: "demo-candidate-3",
    comment_id: "c17a",
    status: "pending",
    applied_at: hoursAgo(3),
  },
  {
    id: "demo-application-18",
    post_id: "demo-post-18",
    candidate_id: "demo-candidate-4",
    comment_id: "c18a",
    status: "approved",
    applied_at: hoursAgo(8),
  },
  {
    id: "demo-application-19",
    post_id: "demo-post-19",
    candidate_id: "demo-candidate-5",
    comment_id: "c19a",
    status: "rejected",
    applied_at: hoursAgo(11),
  },
  {
    id: "demo-application-20",
    post_id: "demo-post-20",
    candidate_id: "demo-candidate-1",
    comment_id: "c20a",
    status: "approved",
    applied_at: hoursAgo(14),
  },
  {
    id: "demo-application-21a",
    post_id: "demo-post-21",
    candidate_id: "demo-candidate-2",
    comment_id: "c21a",
    status: "pending",
    applied_at: hoursAgo(19),
  },
  {
    id: "demo-application-21b",
    post_id: "demo-post-21",
    candidate_id: "demo-candidate-3",
    comment_id: "c21b",
    status: "approved",
    applied_at: hoursAgo(18),
  },
  {
    id: "demo-application-21c",
    post_id: "demo-post-21",
    candidate_id: "demo-candidate-4",
    comment_id: "c21c",
    status: "rejected",
    applied_at: hoursAgo(17),
  },
  {
    id: "demo-application-22",
    post_id: "demo-post-22",
    candidate_id: "demo-candidate-5",
    comment_id: "c22a",
    status: "approved",
    applied_at: hoursAgo(22),
  },
];

export const DEMO_REPORTS: Report[] = [
  {
    id: "demo-report-20",
    reporter_id: "demo-candidate-1",
    reporter: demoUser("demo-candidate-1"),
    target_post_id: "demo-post-20",
    post: DEMO_POSTS.find((post) => post.id === "demo-post-20"),
    reason: "Sau khi CV duoc duyet, noi dung trao doi ve muc luong va scope cong viec khong giong bai dang.",
    status: "pending",
    reviewed_by: null,
    reviewed_at: null,
    created_at: hoursAgo(12),
  },
  {
    id: "demo-report-22",
    reporter_id: "demo-candidate-5",
    reporter: demoUser("demo-candidate-5"),
    target_post_id: "demo-post-22",
    post: DEMO_POSTS.find((post) => post.id === "demo-post-22"),
    reason: "Bai dang freelance nhung khi lien he thi yeu cau dat coc va thong tin thanh toan mo ho.",
    status: "pending",
    reviewed_by: null,
    reviewed_at: null,
    created_at: hoursAgo(21),
  },
];
